config/routes.rb
Rails.application.routes.draw do


  get 'homes/show'

  get "dashboard", to: "dashboards#show"

  devise_for :users

  resources :dogs do
    resources :appointments, only: [:new, :create]
  end
  resources :appointments, only: [:show, :edit, :update, :destroy]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  enum status: [ :pending, :confirmed, :declined ]

end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  belongs_to :breed
  has_many :appointments

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :dogs
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = policy_scope(Appointment)
  end

  def show
    @appointments = Appointment.find(params[:id])
  end

  def new
    @appointment = current_user.appointments.new
    authorize @appointment
  end

  def create
    @appointment = current_user.appointments.new(appointment_params)
    @appointment.dog = Dog.find(params[:dog_id])
    authorize @appointment
    if @appointment.save
      redirect_to dashboard_path, notice: "Appointment created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @appointment.update(appointment_status_params)
    redirect_to dashboard_path
  end

  def destroy
    @appointment.destroy
    redirect_to dashboard_path
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
    authorize @appointment
  end

  def appointment_params
    params.require(:appointment).permit(:date, :message, :status, :user_id, :dog_id)
  end

  def appointment_status_params
    params.permit(:status)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user
    @dogs = current_user.dogs
    @appointments = current_user.appointments
    authorize @dogs
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  def index
    @text_input_from_user = params["search-word"]
    @dogs = policy_scope(Dog)
    if params.has_key?("search-word")
      @dogs = Dog.where('address LIKE ?', "%#{@text_input_from_user.capitalize}%")
    else
      @dogs = Dog.all
    end

    @dogsT = @dogs.where.not(latitude: nil, longitude: nil)
    @markers = @dogsT.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
      }
    end
  end

  def show
    @appointment = Appointment.new
    @marker = []
    @marker = [{lat: @dog.latitude, lng: @dog.longitude }] if @dog.latitude && @dog.longitude
  end

  def new
    @dog = current_user.dogs.new
    authorize @dog
  end

  def create
    @dog = current_user.dogs.new(dogs_params)
    authorize @dog
    if @dog.save
      redirect_to @dog
    else
      render :new
    end
  end

  def edit

  end

  def update
    @dog.update(dogs_params)
    redirect_to @dog
  end

  def destroy
    @dog.destroy
    redirect_to dogs_path
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
    authorize @dog
  end

  def dogs_params
    params.require(:dog).permit(:name, :photo, :age, :pedigree, :description, :address, :user_id, :breed_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   skip_before_action :authenticate_user!

  def home
    @dogs = Dog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<h1>Appointments#form</h1>
<p>Find me in app/views/appointments/_form.html.erb</p>

<%= simple_form_for(@appointment) do |f| %>
<%= f.input :date, as :date, html5 :true %>
<%= f.input :message %>
<%= f.button :submit %>
<% end %>

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<% @appointments.each do |appointment| %>
<%= appointment.name %>
<% end %>

app/views/appointments/new.html.erb
<%= render 'form' %>

app/views/appointments/show.html.erb
<%= @appointment.message %>
<%= @appointment.date %>

app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

app/views/dashboards/show.html.erb
<div class="dashboard-intro-box">
  <h3>Welcome to your dashboard <%= @user.first_name %></h3>
</div>



<div class="dashboard-appointment-container">
  <h2><i class="far fa-calendar-check app-icon"></i> your appointments</h2>
  <ul class="nav nav-tabs">
    <li class="active">
      <a data-toggle="tab" href="#appointments-requested" class="menu-item">Appointments you requested</a>
    </li>
    <li>
      <a data-toggle="tab" href="#appointments-invited" class="menu-item">Appointments you've been invited to</a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="appointments-requested" class="tab-pane fade in active">
      <div class="panel-group">
        <% @appointments.each do |appointment| %>
        <div class="panel panel-success appointment-item">
          <div class="panel-heading <%= appointment.status %>">
            <p>Appointment date: <%= appointment.date.strftime("%B %d, %Y")%></p>
            <p><em><%= appointment.status.capitalize %></em></p>
          </div>
          <div class="panel-body">
            <p>You requested to check out <%= link_to appointment.dog.name, dog_path(appointment.dog), class: "link-to-dog-show" %></p>
            <em><p class="app-message"><%= appointment.message %></em></p>
            <p><%= link_to "Cancel appointment", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure to delete this appointment?" }, class: "btn btn-danger app-button" %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>


    <div id="appointments-invited" class="tab-pane fade">
      <div class="panel-group">
        <% @dogs.each do |dog| %>
        <% dog.appointments.each do |appointment| %>
        <div class="panel panel-primary appointment-item">
          <div class="panel-heading <%= appointment.status %>">
            <p>Appointment date: <%= appointment.date.strftime("%B %d, %Y")%></p>
            <p><em><%= appointment.status.capitalize %></em></p>
          </div>
          <div class="panel-body">
            <p><%= appointment.user.first_name %> wrote you about <%= link_to appointment.dog.name, dog_path(appointment.dog), class: "link-to-dog-show" %> :</p>
            <em><p class="app-message"><%= appointment.message %></em></p>
            <div class="inline-buttons">
              <p><%= link_to "Confirm appointment", appointment_path(appointment, :status => "confirmed"), :method => :put, class: "btn btn-success app-button" %></p>
              <p><%= link_to "Decline appointment", appointment_path(appointment, :status => "declined"), :method => :put, class: "btn btn-primary app-button" %></p>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="dashboard-dog-container">
  <h2><%= image_tag 'o.png', height: '44' %> your dogs</h2>

  <div class="container">
    <div class="row">
      <% @dogs.each do |dog| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to(dog_path(dog)) do %>
        <% if dog.photo == nil %>
        <div class="dashboard-dog-item" style="background-image: url(<%= asset_url('doge.jpg') %>)"> <h4><%= dog.name %></h4></div>
        <% else %>
        <div class="dashboard-dog-item" style="background-image: url(<%= dog.photo %>)"> <h4><%= dog.name %></h4></div>
        <% end %>
        <% end %>
      </div>
      <% end %>

      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to(new_dog_path) do %>
        <div class="dashboard-dog-item add-dog-card" style="background-image: url(<%= asset_url('add-dog.jpg') %>)"> <h5><em>Want to add a new dog?</em></h5></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/_form.html.erb
<div class="container-form-wrapper">
<%= simple_form_for @dog, :html => {class: "form-input"}  do |f| %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.input :photo %>
<%= f.input :age %>
<%= f.association :breed %>
<%= f.button :submit %>
<% end %>
</div>

app/views/dogs/create.html.erb
<h1>Dogs#create</h1>
<p>Find me in app/views/dogs/create.html.erb</p>

app/views/dogs/destroy.html.erb
<h1>Dogs#destroy</h1>
<p>Find me in app/views/dogs/destroy.html.erb</p>

app/views/dogs/edit.html.erb
<%= render 'form' %>

app/views/dogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="flash-notice"><%= flash[:notice] %></p>
      <div class="container-index-search-bar">
        <div>
          <form action="#" class="form-inline">
            <input type="text" id="form-input" class="form-control input-lg" placeholder="Where?">
            <input type="submit" class="btn btn-primary btn-lg" value="Search">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-9">
     <% @dogs.each do |dog| %>
     <div class="col-xs-4">
      <%= link_to(dog_path(dog)) do %>
      <% if dog.photo == nil %>

      <div class="index-dog-item" style="background-image: url(<%= asset_url('doge.jpg') %>)">
        <div class="dogcaption">
          <h5><%= dog.breed.name %>, <%= dog.age %> </h5>
        </div>
      </div>



      <% else %>

      <div class="index-dog-item" style="background-image: url(<%= dog.photo %>)">
        <div class="dogcaption">
          <% if dog.age < 12 %>
          <h5><%= dog.breed.name.capitalize %>, <%= dog.age %> months </h5>
          <% else %>
          <h5><%= dog.breed.name.capitalize %>, <%= (dog.age)/12.round %> years </h5>
          <% end %>
        </div>
      </div>


      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="col-xs-3">
    <div id="map" class="index-map" data-markers="<%= @markers.to_json %>"></div>
  </div>
</div>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/dogs/show.html.erb
<div class="container">
  <div class="container-main">
    <div class="basic-info-show" data-spy="affix">
      <% if current_user != @dog.user %>
        <div class="inline-container"><h4>Name: </h4><p><%= @dog.name %></p class="inline-container"></div>

        <div class="inline-container"><h4>Age: </h4><p>
          <% if @dog.age < 12 %>
            <%= @dog.age %> months
          <% else %>
            <%= (@dog.age)/12.round %> years
          <% end %>
        </p></div>

        <div class="inline-container"><h4>Pedigree: </h4><p><%= @dog.pedigree %></p></div>
        <div class="inline-container"><h4>Breed: </h4><p><%= @dog.breed.name %></p></div>
        <div class="inline-container"><h4>Address: </h4><p><%= @dog.address %></p></div>
      <button type="button" class="btn request-appt" data-toggle="modal" data-target="#exampleModal">
        Ask <%= @dog.user.first_name %> to meet <%= @dog.name %>
      </button>
      <% else %>
      <%= link_to("This is your dog!! Go to dashboard", dashboard_path, html_options = {class: "btn btn-primary"}) %>
      <% end %>
    </div>
  </div>

  <div class="photo-container" style="background-image: url(<%= @dog.photo %>);">
  </div>

  <div class="description col-sm-6 col-offset-sm-6">
    <h4>Description: </h4><p><%= @dog.description %></p>
  </div>

  <div
  id="map"
  class="show-map"
  data-markers="<%= @marker.to_json %>"
  ></div>

  <%= render 'shared/modal' %>
</div>

app/views/dogs/update.html.erb
<h1>Dogs#update</h1>
<p>Find me in app/views/dogs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dog Corner - Adopt your dog in a few clicks</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.2) 100%), url('https://images.unsplash.com/photo-1444212477490-ca407925329e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=86d24240ca6b1df611e98ed6bd7a1efc&auto=format&fit=crop&w=1100&q=80');">
  <div class="banner-content">

    <div class="text">
     <%= image_tag "wlogo.png" %>
     <p class="text-description">Adopt your dog in a few clicks</p>
   </div>

   <form action="dogs" class="form-inline">
     <input  name="search-word" type="text" class="form-control input-lg form-input" placeholder="Where?">
     <input type="submit" class="btn btn-primary btn-lg" value="Search">
   </form>
 </div>
</div>


<h3 class="home-subtitle">Last dogs added to Dog Corner</h3>
<div class="home-wrapper">
<div class="row">
 <% @dogs.first(3).each do |dog| %>
 <div class="col-xs-4">
  <%= link_to(dog_path(dog)) do %>
  <% if dog.photo == nil %>

  <div class="index-dog-item home-card" style="background-image: url(<%= asset_url('doge.jpg') %>)">
    <div class="dogcaption home-caption">
      <h5><%= dog.breed.name %>, <%= dog.age %> </h5>
    </div>
  </div>



  <% else %>

  <div class="index-dog-item home-card" style="background-image: url(<%= dog.photo %>)">
    <div class="dogcaption home-caption">
      <% if dog.age < 12 %>
      <h5><%= dog.breed.name.capitalize %>, <%= dog.age %> months </h5>
      <% else %>
      <h5><%= dog.breed.name.capitalize %>, <%= (dog.age)/12.round %> years </h5>
      <% end %>
    </div>
  </div>


  <% end %>
  <% end %>
</div>
<% end %>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h4>Contact <%= @dog.user.first_name %> to request an appointment to see <%= @dog.name %> the dog</h4>
        <%= simple_form_for([@dog, @appointment]) do |f| %>
        <%= f.input :date, as: :date, html5: true %>
        <%= f.input :message %>
        <div class="modal-footer">
          <%= f.button :submit, :label_html => { class: 'btn-dark' } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="global_nav" class="navbar-wagon navbar-default navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "doglogo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "Add Dog", new_dog_path, class: "navbar-wagon-item navbar-wagon-link" %>

        </li>
        <li>
          <%= link_to "Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>